In [9]:
import pandas as pd

In [10]:
cust = pd.read_csv('customers.csv')
sal  = pd.read_csv('sales.csv')

In [12]:
cust.head()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,46-55,1977-01-13,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,65+,1952-01-20,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24
2,CUST00000003,Suresh Kumar,male,31,26-35,1994-01-09,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,Silver,0,0.00
3,CUST00000004,Aditya Pandey,male,41,36-45,1984-01-12,adityapandey@outlook.com,+91-9015046072,Kolkata,West Bengal,735356,2024-03-11,Platinum,5,288324.84
4,CUST00000005,Hina Khan,female,53,46-55,1972-01-15,hinakhan433@gmail.com,+91-8813094271,Noida,UP,985141,2024-04-19,Platinum,4,69265.75

In [14]:
sal.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45

In [20]:
cust.shape

(40000, 15)

In [21]:
sal.shape

(250000, 21)

In [22]:
cust.duplicated().sum()

np.int64(0)

In [23]:
sal.duplicated().sum()

np.int64(0)

In [24]:
cust.isnull().sum()

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
Age_Group            0
Date_of_Birth        0
Email                0
Phone                0
City                 0
State                0
Pincode              0
Registration_Date    0
Customer_Tier        0
Total_Orders         0
Total_Spent          0
dtype: int64

In [25]:
sal.isnull().sum()

Order_ID                   0
Customer_ID                0
Product_ID                 0
Order_Date                 0
Order_Time                 0
Delivery_Date              0
Quantity                   0
Unit_Price                 0
Order_Value                0
Shipping_Cost              0
Coupon_Code           199815
Coupon_Discount            0
Total_Amount               0
Payment_Mode               0
Order_Status               0
Rating                129970
Review_Text           129970
City                       0
State                      0
Customer_Age               0
Customer_Age_Group         0
dtype: int64

In [36]:
sal['Coupon_Code'].isna().mean() * 100

np.float64(79.926)

In [39]:
sal.head()

,Order_ID,Customer_ID,Product_ID,Order_Date,Order_Time,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,...,Coupon_Discount,Total_Amount,Payment_Mode,Order_Status,Rating,Review_Text,City,State,Customer_Age,Customer_Age_Group
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,08:20:00,2026-06-10,1,2622.46,2622.46,0.0,...,0.0,2622.46,COD,Delivered,NaN,NaN,Chennai,Tamil Nadu,43,36-45
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,20:05:00,2025-02-07,1,90258.00,90258.00,0.0,...,0.0,90258.00,COD,Delivered,4.0,Nice quality,Durgapur,West Bengal,22,18-25
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,14:59:00,2026-03-19,1,3536.50,3536.50,0.0,...,0.0,3536.50,UPI,Processing,NaN,NaN,Patiala,Punjab,41,36-45
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,14:33:00,2025-02-02,1,34081.56,34081.56,0.0,...,50.0,34031.56,Credit Card,Delivered,NaN,NaN,Rajkot,Gujarat,29,26-35
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,07:19:00,2024-07-02,2,69021.17,138042.34,0.0,...,0.0,138042.34,UPI,Delivered,NaN,NaN,Surat,Gujarat,39,36-45

In [46]:
sal['Coupon_Code'].sample(10)

55435           NaN
31003           NaN
193447          NaN
206581          NaN
74968           NaN
140542          NaN
37746           NaN
203873    DIWALI100
109613          NaN
25551           NaN
Name: Coupon_Code, dtype: object

In [48]:
sal.loc[sal['Coupon_Code'].isna(),
    'Coupon_Discount'].describe()

count    199815.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: Coupon_Discount, dtype: float64

In [51]:
sal.assign(
    Coupon_Missing=sal['Coupon_Code'].isna()
).groupby('Coupon_Missing').agg(
    Orders=('Order_ID', 'count'),
    Avg_Discount=('Coupon_Discount', 'mean'),
    Avg_Order_Value=('Order_Value', 'mean'),
    Avg_Total_Amount=('Total_Amount', 'mean')
)

                Orders  Avg_Discount  Avg_Order_Value  Avg_Total_Amount
Coupon_Missing
False            50185   1245.397759     24299.943991      23059.377387
True            199815      0.000000     23884.457417      23889.389686

In [53]:
sal.loc[
    sal['Coupon_Code'].isna(),
    ['Coupon_Code', 'Coupon_Discount',
     'Order_Value', 'Total_Amount']
].sample(10, random_state=42)

       Coupon_Code  Coupon_Discount  Order_Value  Total_Amount
58088          NaN              0.0      9590.92       9590.92
54872          NaN              0.0      3682.86       3682.86
85802          NaN              0.0      1691.54       1691.54
63306          NaN              0.0      6266.52       6266.52
116724         NaN              0.0      1292.85       1292.85
28935          NaN              0.0     17686.67      17686.67
84599          NaN              0.0      7196.38       7196.38
187199         NaN              0.0      3722.40       3722.40
244028         NaN              0.0       961.98        961.98
99177          NaN              0.0      5525.13       5525.13

In [55]:
sal['Coupon_Code'] = sal['Coupon_Code'].fillna('No Coupon')

In [56]:
sal['Coupon_Code'].isna().sum()
sal['Coupon_Code'].value_counts().head(10)

Coupon_Code
No Coupon    199815
SAVE10        24997
DIWALI100     12609
FLAT50        12579
Name: count, dtype: int64

In [57]:
sal.isnull().sum()

Order_ID                   0
Customer_ID                0
Product_ID                 0
Order_Date                 0
Order_Time                 0
Delivery_Date              0
Quantity                   0
Unit_Price                 0
Order_Value                0
Shipping_Cost              0
Coupon_Code                0
Coupon_Discount            0
Total_Amount               0
Payment_Mode               0
Order_Status               0
Rating                129970
Review_Text           129970
City                       0
State                      0
Customer_Age               0
Customer_Age_Group         0
dtype: int64

In [59]:
sal['Rating'].isnull().mean() * 100

np.float64(51.988)

In [62]:
sal['Rating'].value_counts(dropna=False).sort_index()

Rating
3.0     12057
4.0     47976
5.0     59997
NaN    129970
Name: count, dtype: int64

In [65]:
sal.groupby(sal['Rating'].isna()).agg(
    orders=('Order_ID', 'count'),
    reviews_missing=('Review_Text',
                    lambda x: x.isna().sum())
)

        orders  reviews_missing
Rating
False   120030                0
True    129970           129970

In [73]:
sal['Rating'].mean()

np.float64(4.399400149962509)

In [76]:
sal.groupby(sal['Rating'].isna())['Order_Status'].value_counts()

Rating  Order_Status
False   Delivered       120030
True    Delivered        80109
        Cancelled        12507
        Returned         12493
        Shipped          12459
        Processing       12402
Name: count, dtype: int64

**Data Cleaning Insight — Rating Column ⭐**

The `Rating` column contains 129,970 missing values, and all of them coincide with missing `Review_Text`. Further investigation revealed that ratings are available only for delivered orders, while some delivered orders also lack customer feedback.

**Cleaning decision:** Preserved missing ratings as `NULL` instead of imputing artificial values or deleting records. These missing values may represent customers who did not submit feedback, although the underlying reason cannot be confirmed from the data alone.

**Business impact:** Retaining these records preserves valuable sales and operational information while ensuring that customer satisfaction metrics are calculated only from actual ratings.

**Key takeaway:** Not every missing value is a data-quality problem. Sometimes, preserving missingness is the most accurate analytical decision.

In [81]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order_ID            250000 non-null  object
 1   Customer_ID         250000 non-null  object
 2   Product_ID          250000 non-null  object
 3   Order_Date          250000 non-null  object
 4   Order_Time          250000 non-null  object
 5   Delivery_Date       250000 non-null  object
 6   Quantity            250000 non-null  int64
 7   Unit_Price          250000 non-null  float64
 8   Order_Value         250000 non-null  float64
 9   Shipping_Cost       250000 non-null  float64
 10  Coupon_Code         250000 non-null  object
 11  Coupon_Discount     250000 non-null  float64
 12  Total_Amount        250000 non-null  float64
 13  Payment_Mode        250000 non-null  object
 14  Order_Status        250000 non-null  object
 15  Rating              120030 non-null  float64
 16  Review_Text         120030 non-null  object
 17  City                250000 non-null  object
 18  State               250000 non-null  object
 19  Customer_Age        250000 non-null  int64
 20  Customer_Age_Group  250000 non-null  object
dtypes: float64(6), int64(2), object(13)
memory usage: 40.1+ MB

In [83]:
sal['Order_Date'] = pd.to_datetime(sal['Order_Date'], errors='coerce')
sal['Delivery_Date'] = pd.to_datetime(sal['Delivery_Date'], errors='coerce')

sal.dtypes

Order_ID                      object
Customer_ID                   object
Product_ID                    object
Order_Date            datetime64[ns]
Order_Time                    object
Delivery_Date         datetime64[ns]
Quantity                       int64
Unit_Price                   float64
Order_Value                  float64
Shipping_Cost                float64
Coupon_Code                   object
Coupon_Discount              float64
Total_Amount                 float64
Payment_Mode                  object
Order_Status                  object
Rating                       float64
Review_Text                   object
City                          object
State                         object
Customer_Age                   int64
Customer_Age_Group            object
dtype: object

In [85]:
sal[['Order_Date', 'Delivery_Date']].isna().sum()

Order_Date       0
Delivery_Date    0
dtype: int64

In [86]:
sal['Order_Date'] = pd.to_datetime(sal['Order_Date'], errors='coerce')
sal['Delivery_Date'] = pd.to_datetime(sal['Delivery_Date'], errors='coerce')

sal['Order_Time'] = pd.to_datetime(
    sal['Order_Time'], format='%H:%M:%S', errors='coerce'
).dt.time

In [87]:
cat_cols = [
    'Payment_Mode', 'Order_Status', 'City',
    'State', 'Customer_Age_Group'
]

sal[cat_cols] = sal[cat_cols].astype('category')

In [88]:
num_cols = [
    'Quantity', 'Unit_Price', 'Order_Value',
    'Shipping_Cost', 'Coupon_Discount',
    'Total_Amount', 'Rating', 'Customer_Age'
]

print(sal[num_cols].dtypes)

Quantity             int64
Unit_Price         float64
Order_Value        float64
Shipping_Cost      float64
Coupon_Discount    float64
Total_Amount       float64
Rating             float64
Customer_Age         int64
dtype: object

In [89]:
sal[['Order_Date', 'Delivery_Date', 'Order_Time']].isna().sum()

Order_Date       0
Delivery_Date    0
Order_Time       0
dtype: int64

In [90]:
# Negative or zero quantities
print("Quantity <= 0:", (sal['Quantity'] <= 0).sum())

# Negative prices and costs
for col in ['Unit_Price', 'Order_Value', 'Shipping_Cost',
            'Coupon_Discount', 'Total_Amount']:
    print(f"{col} < 0:", (sal[col] < 0).sum())

# Zero prices and costs
for col in ['Unit_Price', 'Order_Value', 'Total_Amount']:
    print(f"{col} == 0:", (sal[col] == 0).sum())

Quantity <= 0: 0
Unit_Price < 0: 0
Order_Value < 0: 0
Shipping_Cost < 0: 0
Coupon_Discount < 0: 0
Total_Amount < 0: 5
Unit_Price == 0: 0
Order_Value == 0: 0
Total_Amount == 0: 0

In [91]:
print(sal.columns.tolist())

['Order_ID', 'Customer_ID', 'Product_ID', 'Order_Date', 'Order_Time', 'Delivery_Date', 'Quantity', 'Unit_Price', 'Order_Value', 'Shipping_Cost', 'Coupon_Code', 'Coupon_Discount', 'Total_Amount', 'Payment_Mode', 'Order_Status', 'Rating', 'Review_Text', 'City', 'State', 'Customer_Age', 'Customer_Age_Group']

In [92]:
print(sal['Order_Status'].value_counts(dropna=False))

Order_Status
Delivered     200139
Cancelled      12507
Returned       12493
Shipped        12459
Processing     12402
Name: count, dtype: int64

In [93]:
sal['Calculated_Order_Value'] = (
    sal['Quantity'] * sal['Unit_Price']
)

sal['Order_Value_Difference'] = (
    sal['Order_Value'] - sal['Calculated_Order_Value']
)

print(
    "Mismatched orders:",
    (sal['Order_Value_Difference'].abs() > 0.01).sum()
)

Mismatched orders: 0

In [94]:
sal[[
    'Quantity', 'Unit_Price', 'Order_Value',
    'Coupon_Discount', 'Shipping_Cost', 'Total_Amount'
]].head(10)

,Quantity,Unit_Price,Order_Value,Coupon_Discount,Shipping_Cost,Total_Amount
0,1,2622.46,2622.46,0.00,0.0,2622.46
1,1,90258.00,90258.00,0.00,0.0,90258.00
2,1,3536.50,3536.50,0.00,0.0,3536.50
3,1,34081.56,34081.56,50.00,0.0,34031.56
4,2,69021.17,138042.34,0.00,0.0,138042.34
5,1,4489.77,4489.77,50.00,0.0,4439.77
6,2,33620.99,67241.98,0.00,0.0,67241.98
7,2,1161.62,2323.24,232.32,0.0,2090.92
8,1,22456.69,22456.69,2245.67,0.0,20211.02
9,1,86647.71,86647.71,0.00,0.0,86647.71

In [95]:
sal.drop(
    columns=['Calculated_Order_Value', 'Order_Value_Difference'],
    inplace=True
)

In [97]:
sal.columns

Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Order_Date', 'Order_Time',
       'Delivery_Date', 'Quantity', 'Unit_Price', 'Order_Value',
       'Shipping_Cost', 'Coupon_Code', 'Coupon_Discount', 'Total_Amount',
       'Payment_Mode', 'Order_Status', 'Rating', 'Review_Text', 'City',
       'State', 'Customer_Age', 'Customer_Age_Group'],
      dtype='object')

In [98]:
sal.to_csv("sales_cleaned.csv", index=False)

In [99]:
cust.info()
cust.head()
cust.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        40000 non-null  object
 1   Customer_Name      40000 non-null  object
 2   Gender             40000 non-null  object
 3   Age                40000 non-null  int64
 4   Age_Group          40000 non-null  object
 5   Date_of_Birth      40000 non-null  object
 6   Email              40000 non-null  object
 7   Phone              40000 non-null  object
 8   City               40000 non-null  object
 9   State              40000 non-null  object
 10  Pincode            40000 non-null  int64
 11  Registration_Date  40000 non-null  object
 12  Customer_Tier      40000 non-null  object
 13  Total_Orders       40000 non-null  int64
 14  Total_Spent        40000 non-null  float64
dtypes: float64(1), int64(3), object(11)
memory usage: 4.6+ MB

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
count,40000,40000,40000,40000.000000,40000,40000,40000,40000,40000,40000,40000.000000,40000,40000,40000.000000,40000.00000
unique,40000,927,2,NaN,6,58,26567,40000,39,10,NaN,366,3,NaN,NaN
top,CUST00039984,Swati Patel,male,NaN,26-35,1996-01-09,riyagupta@yahoo.com,+91-7317511701,New Delhi,UP,NaN,2023-08-24,Platinum,NaN,NaN
freq,1,82,20003,NaN,14059,1466,16,1,1105,5218,NaN,146,27349,NaN,NaN
mean,NaN,NaN,NaN,35.306225,NaN,NaN,NaN,NaN,NaN,NaN,549135.098375,NaN,NaN,5.003475,118539.15886
std,NaN,NaN,NaN,12.581443,NaN,NaN,NaN,NaN,NaN,NaN,259430.688860,NaN,NaN,2.232485,106205.42346
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,100010.000000,NaN,NaN,0.000000,0.00000
25%,NaN,NaN,NaN,26.000000,NaN,NaN,NaN,NaN,NaN,NaN,325689.750000,NaN,NaN,3.000000,37814.14750
50%,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,NaN,NaN,547573.500000,NaN,NaN,5.000000,90059.66000
75%,NaN,NaN,NaN,43.000000,NaN,NaN,NaN,NaN,NaN,NaN,773876.000000,NaN,NaN,6.000000,169958.41750
max,NaN,NaN,NaN,75.000000,NaN,NaN,NaN,NaN,NaN,NaN,999986.000000,NaN,NaN,17.000000,890131.55000

In [100]:
cust['Date_of_Birth'] = pd.to_datetime(
    cust['Date_of_Birth'], errors='coerce'
)

cust['Registration_Date'] = pd.to_datetime(
    cust['Registration_Date'], errors='coerce'
)

cust['Pincode'] = cust['Pincode'].astype('string')
cust['Phone'] = cust['Phone'].astype('string')
cust['Customer_ID'] = cust['Customer_ID'].astype('string')

In [101]:
for col in ['Gender', 'Age_Group', 'City', 'State', 'Customer_Tier']:
    print(f"\n{col}:")
    print(cust[col].value_counts())

Gender:
Gender
male      20003
female    19997
Name: count, dtype: int64

Age_Group:
Age_Group
26-35    14059
18-25     9876
36-45     8011
46-55     4841
56-65     2437
65+        776
Name: count, dtype: int64

City:
City
New Delhi     1105
Madurai       1104
Howrah        1099
Kanpur        1075
Patiala       1071
Varanasi      1071
Chennai       1069
Amritsar      1067
Alwar         1057
Kolkata       1041
Palwal        1038
Surat         1037
Dwarka        1036
Agra          1036
Vadodara      1033
Sohna         1032
Mysore        1031
Thane         1031
Mangalore     1027
Lucknow       1026
Jaipur        1022
Panipat       1022
Mumbai        1021
Gurugram      1018
Nagpur        1016
Faridabad     1014
Noida         1010
Durgapur      1000
Jodhpur        998
Coimbatore     997
Ludhiana       995
Udaipur        994
Rajkot         986
Kota           986
Pune           982
Delhi NCR      975
Ahmedabad      970
Bangalore      958
Jalandhar      950
Name: count, dtype: int64

State:
State
UP             5218
Haryana        5124
Rajasthan      5057
Punjab         4083
Maharashtra    4050
Gujarat        4026
Tamil Nadu     3170
West Bengal    3140
Delhi          3116
Karnataka      3016
Name: count, dtype: int64

Customer_Tier:
Customer_Tier
Platinum    27349
Gold         6692
Silver       5959
Name: count, dtype: int64

In [102]:
for col in ['Gender', 'Age_Group', 'City', 'State', 'Customer_Tier']:
    cust[col] = cust[col].str.strip()

In [103]:
print("Age below 18 or above 100:",
      ((cust['Age'] < 18) | (cust['Age'] > 100)).sum())

print("Negative orders:", (cust['Total_Orders'] < 0).sum())

print("Negative spending:", (cust['Total_Spent'] < 0).sum())

Age below 18 or above 100: 0
Negative orders: 0
Negative spending: 0

In [104]:
today = pd.Timestamp.today().normalize()

calculated_age = (
    today.year - cust['Date_of_Birth'].dt.year
    - (
        (today.month < cust['Date_of_Birth'].dt.month)
        | (
            (today.month == cust['Date_of_Birth'].dt.month)
            & (today.day < cust['Date_of_Birth'].dt.day)
        )
    )
)

print("Age mismatches:", (cust['Age'] != calculated_age).sum())

Age mismatches: 40000

In [105]:
print(
    "Registration before birth:",
    (cust['Registration_Date'] < cust['Date_of_Birth']).sum()
)

print(cust.groupby('Customer_Tier').agg(
    Customers=('Customer_ID', 'count'),
    Avg_Orders=('Total_Orders', 'mean'),
    Avg_Spending=('Total_Spent', 'mean')
).round(2))

Registration before birth: 0
               Customers  Avg_Orders  Avg_Spending
Customer_Tier
Gold                6692        4.28      34733.20
Platinum           27349        5.61     162907.79
Silver              5959        3.02       9022.78

In [106]:
cust.to_csv('customers_cleaned.csv', index=False)