In [47]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('ecommerce.db')

# Sales dataset
sal = pd.read_csv('sales_cleaned.csv')
sal.to_sql('sales', conn, if_exists='replace', index=False)

# Customers dataset
cust = pd.read_csv('customers_cleaned.csv')
cust.to_sql('customers', conn, if_exists='replace', index=False)

40000

In [48]:
columns = [
    'Age_Group',
    'Date_of_Birth',
    'Email',
    'Phone',
    'Pincode',
    'Registration_Date',
    'Customer_Tier'
]

for col in columns:
    conn.execute(f'ALTER TABLE customers DROP COLUMN "{col}"')

conn.commit()

In [49]:
pd.read_sql_query("""
SELECT * FROM customers """, conn)

,Customer_ID,Customer_Name,Gender,Age,City,State,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,Patiala,Punjab,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,Durgapur,West Bengal,8,63676.24
2,CUST00000003,Suresh Kumar,male,31,Gurugram,Haryana,0,0.00
3,CUST00000004,Aditya Pandey,male,41,Kolkata,West Bengal,5,288324.84
4,CUST00000005,Hina Khan,female,53,Noida,UP,4,69265.75
...,...,...,...,...,...,...,...,...
39995,CUST00039996,Swati Joshi,female,43,Mysore,Karnataka,4,137030.99
39996,CUST00039997,Nikhil Patel,male,33,Mumbai,Maharashtra,8,193564.72
39997,CUST00039998,Akash Yadav,male,24,Ahmedabad,Gujarat,6,191316.63
39998,CUST00039999,Salman Ansari,male,52,Mysore,Karnataka,2,6482.53
39999,CUST00040000,Ahmed Ahmed,male,34,Ahmedabad,Gujarat,8,216922.80

In [50]:
columns = [
    'Order_Time',
    'Coupon_Code',
    'Review_Text',
    'Customer_Age',
    'Customer_Age_Group',
    'Rating',
    'City',
    'State',
    'payment_Mode'
]

for col in columns:
    conn.execute(f'ALTER TABLE sales DROP COLUMN "{col}"')

conn.commit()

In [51]:
pd.read_sql_query("""
SELECT * FROM sales """, conn)

,Order_ID,Customer_ID,Product_ID,Order_Date,Delivery_Date,Quantity,Unit_Price,Order_Value,Shipping_Cost,Coupon_Discount,Total_Amount,Order_Status
0,ORD0000000001,CUST00014303,PROD001017,2026-06-07,2026-06-10,1,2622.46,2622.46,0.0,0.0,2622.46,Delivered
1,ORD0000000002,CUST00034253,PROD000703,2025-02-04,2025-02-07,1,90258.00,90258.00,0.0,0.0,90258.00,Delivered
2,ORD0000000003,CUST00000421,PROD000318,2026-03-12,2026-03-19,1,3536.50,3536.50,0.0,0.0,3536.50,Processing
3,ORD0000000004,CUST00026507,PROD000213,2025-01-27,2025-02-02,1,34081.56,34081.56,0.0,50.0,34031.56,Delivered
4,ORD0000000005,CUST00009418,PROD001437,2024-06-30,2024-07-02,2,69021.17,138042.34,0.0,0.0,138042.34,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
249995,ORD0000249996,CUST00008137,PROD001818,2024-10-06,2024-10-08,1,1827.96,1827.96,0.0,0.0,1827.96,Processing
249996,ORD0000249997,CUST00027003,PROD000955,2024-08-28,2024-08-31,1,4040.86,4040.86,0.0,0.0,4040.86,Delivered
249997,ORD0000249998,CUST00027511,PROD001894,2025-12-09,2025-12-12,2,10516.60,21033.20,0.0,0.0,21033.20,Delivered
249998,ORD0000249999,CUST00022175,PROD001950,2025-05-01,2025-05-05,1,7847.77,7847.77,0.0,0.0,7847.77,Delivered
249999,ORD0000250000,CUST00001621,PROD001213,2025-10-28,2025-10-30,1,18454.82,18454.82,0.0,0.0,18454.82,Delivered

### Which customers have never placed an order?

In [52]:
pd.read_sql_query("""
SELECT c.*
FROM customers c
LEFT JOIN sales s
    ON c.Customer_ID = s.Customer_ID
WHERE s.Customer_ID IS NULL;
""", conn)

,Customer_ID,Customer_Name,Gender,Age,City,State,Total_Orders,Total_Spent
0,CUST00000359,Karan Kumar,male,51,Mysore,Karnataka,0,0.0
1,CUST00001022,Aadhya Shah,female,25,Howrah,West Bengal,0,0.0
2,CUST00001346,Arif Ahmed,male,44,Bangalore,Karnataka,0,0.0
3,CUST00001802,Nisha Kulkarni,female,62,Howrah,West Bengal,0,0.0
4,CUST00002027,Aarav Nair,male,37,Sohna,Haryana,0,0.0
...,...,...,...,...,...,...,...,...
81,CUST00036458,Vishal Yadav,male,32,Kolkata,West Bengal,0,0.0
82,CUST00036739,Neha Mehta,female,30,Udaipur,Rajasthan,0,0.0
83,CUST00037089,Swati Nair,female,49,Agra,UP,0,0.0
84,CUST00037337,Aisha Pathan,female,34,Palwal,Haryana,0,0.0
85,CUST00039852,Riya Gupta,female,35,Alwar,Rajasthan,0,0.0

In [44]:
conn.close()