In [6]:
import sqlite3
import pandas as pd

In [7]:
conn = sqlite3.connect('sales.db')

In [8]:
cursor = conn.cursor()

In [10]:
df = pd.read_csv('sales_data_cleaned.csv')

df.to_sql(
    'sales',
    conn,
    if_exists='replace',
    index=False
)

1894

In [11]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

    name
0  sales

In [13]:
query = """
SELECT * FROM sales
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

,order_id,customer_name,product_category,product_name,units_sold,unit_price,discount_percent,sales_amount,order_date,city,segment,profit
0,1000,Brian Thompson,Jeans,Slim Fit Jeans,0.0,842.000,0.60,0.0,2025-02-27,Delhi,B2C,2137.45
1,1001,Shaun Ross,Jeans,Slim Fit Jeans,1.0,2685.985,0.00,0.0,2025-07-15,Ahmedabad,B2C,1588.15
2,1002,Sarah Snyder,Jackets,Puffer Coat,1.0,637.820,0.00,0.0,2025-01-02,Mumbai,B2B,-158.03
3,1003,Jay Briggs,Shoes,Loafers,2.0,2962.270,0.00,0.0,2025-06-18,bengaluru,B2B,2296.50
4,1005,Samuel Miller,T-Shirts,Crop Top,0.0,2685.985,0.00,0.0,2023-12-05,Mumbai,B2B,1477.73
5,1006,John Mclean,Jeans,Boyfriend Jeans,1.0,2060.850,0.00,0.0,2024-04-02,Ahmedabad,B2B,198.36
6,1009,Dale Perry,T-Shirts,Oversized T-shirt,5.0,2685.985,0.00,0.0,2025-07-20,Bangalore,B2B,-972.73
7,1011,Jacob Sanchez,Accessories,Belts,0.0,2685.985,0.00,0.0,2025-05-27,Delhi,B2C,1370.67
8,1012,Valerie Hampton,Jeans,Straight Cut,4.0,2685.985,0.21,0.0,2024-08-22,Ahmedabad,B2C,843.61
9,1014,Richard Hood,Shoes,Loafers,4.0,2685.985,0.00,0.0,2024-09-21,Hyd,B2C,-889.25

In [14]:
query = """
SELECT
product_name,
SUM(units_sold * unit_price) AS total_revenue
FROM sales
GROUP BY product_name
ORDER BY sales_amount DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

        product_name  total_revenue
0           Sneakers     148986.315
1         Wrap Dress     183931.165
2         Sunglasses     222486.970
3       Straight Cut     229078.435
4           Slip-ons     173378.175
5     Slim Fit Jeans      92542.955
6       Ripped Denim     191267.030
7        Puffer Coat     260935.030
8  Oversized T-shirt     122614.570
9         Maxi Dress     248295.380