In [9]:
import pandas as pd
import sqlite3

# Load cleaned dataset
df = pd.read_csv("advertising_data_cleaned.csv")

# Create a SQLite database
conn = sqlite3.connect("advertising_analysis.db")

# Create a SQL table
df.to_sql(
    "advertising_data",
    conn,
    if_exists="replace",
    index=False
)

print("SQL database and table created successfully!")

SQL database and table created successfully!

#### How can the company optimize advertising spend by identifying which advertising channels, platforms, and creative formats deliver the highest click-through rates at the lowest cost, while staying within budget?

In [16]:
query = "SELECT * FROM advertising_data LIMIT 10;"
pd.read_sql_query(query, conn)

,campaign_item_id,no_of_days,time,ext_service_id,ext_service_name,creative_id,creative_width,creative_height,search_tags,template_id,...,clicks,stats_currency,currency_code,exchange_rate,media_cost_usd,search_tag_cat,cmi_currency_code,timezone,weekday_cat,keywords
0,2733,7,2022-05-01,128,Facebook Ads,1000,300.0,250.0,#The Power of X,90.0,...,8,SGD,SGD,1,14.058514,Others,SGD,Asia/Singapore,week_end,delicate bracelets
1,2733,8,2022-05-02,16,DV360,1000,300.0,250.0,#Be Bold. Be X,90.0,...,44,SGD,SGD,1,99.633496,Others,SGD,Asia/Singapore,week_day,summer jewelry
2,2733,9,2022-05-03,128,Facebook Ads,1000,300.0,250.0,#Embrace Your Individuality with X,90.0,...,32,SGD,SGD,1,109.419677,Others,SGD,Asia/Singapore,week_day,artisan jewelry
3,2733,10,2022-05-04,128,Facebook Ads,1000,300.0,250.0,#Be Bold. Be X,90.0,...,48,SGD,SGD,1,115.209499,Others,SGD,Asia/Singapore,week_day,layered bracelets
4,2733,11,2022-05-05,4,Google Ads,1000,300.0,250.0,#Be Bold. Be X,90.0,...,20,SGD,SGD,1,66.990104,Others,SGD,Asia/Singapore,week_day,minimalist jewelry
5,2766,53,2022-05-31,4,Google Ads,1005,0.0,0.0,#Be Bold. Be X,23.0,...,11,USD,USD,1,35.673124,Youtube,USD,America/New_York,week_day,beaded bracelets
6,2766,54,2022-06-01,4,Google Ads,1005,0.0,0.0,#The Ultimate Fashion Statement with X,23.0,...,18,USD,USD,1,43.150656,Youtube,USD,America/New_York,week_day,bridal jewelry
7,2766,55,2022-06-02,16,DV360,1005,0.0,0.0,#The Ultimate Fashion Statement with X,23.0,...,12,USD,USD,1,31.436393,Youtube,USD,America/New_York,week_day,unique and trendy jewelry
8,2766,56,2022-06-03,16,DV360,1005,0.0,0.0,#The X Factor - Fashion for the Fearless,23.0,...,5,USD,USD,1,5.409166,Youtube,USD,America/New_York,week_day,clip-on earrings
9,2766,57,2022-06-04,128,Facebook Ads,1005,0.0,0.0,#Be Bold. Be X,23.0,...,8,USD,USD,1,5.965384,Youtube,USD,America/New_York,week_day,bohemian jewelry

In [13]:
query = """
SELECT
    channel_name,
    ext_service_name AS advertising_platform,
    creative_width,
    creative_height,

    SUM(impressions) AS total_impressions,
    SUM(clicks) AS total_clicks,
    ROUND(SUM(media_cost_usd), 2) AS total_spend_usd,

    ROUND(
        100.0 * SUM(clicks) / NULLIF(SUM(impressions), 0),
        2
    ) AS ctr_pct,

    ROUND(
        SUM(media_cost_usd) / NULLIF(SUM(clicks), 0),
        4
    ) AS cpc_usd,

    ROUND(
        1000.0 * SUM(media_cost_usd)
        / NULLIF(SUM(impressions), 0),
        2
    ) AS cpm_usd

FROM advertising_data

WHERE impressions > 0
  AND clicks >= 0
  AND clicks <= impressions
  AND media_cost_usd >= 0

GROUP BY
    channel_name,
    ext_service_name,
    creative_width,
    creative_height

HAVING SUM(impressions) >= 1000
   AND SUM(clicks) >= 30

ORDER BY
    ctr_pct DESC,
    cpc_usd ASC;
"""

pd.read_sql_query(query, conn)

,channel_name,advertising_platform,creative_width,creative_height,total_impressions,total_clicks,total_spend_usd,ctr_pct,cpc_usd,cpm_usd
0,Social,DV360,NaN,NaN,1608443,128530,19737.54,7.99,0.1536,12.27
1,Mobile,Google Ads,NaN,NaN,1190918,92889,14463.82,7.80,0.1557,12.15
2,Display,Facebook Ads,NaN,NaN,1335101,102257,13613.26,7.66,0.1331,10.20
3,Video,Facebook Ads,NaN,NaN,1394144,106069,15416.36,7.61,0.1453,11.06
4,Search,Facebook Ads,NaN,NaN,1481104,111488,18640.06,7.53,0.1672,12.59
5,Video,Google Ads,NaN,NaN,1401894,104091,17059.55,7.43,0.1639,12.17
6,Social,Google Ads,NaN,NaN,1283902,92913,13906.29,7.24,0.1497,10.83
7,Display,DV360,NaN,NaN,1616708,116095,19553.01,7.18,0.1684,12.09
8,Mobile,DV360,NaN,NaN,1217370,82538,13527.24,6.78,0.1639,11.11
9,Search,DV360,NaN,NaN,1296671,85727,13943.03,6.61,0.1626,10.75
10,Social,Facebook Ads,NaN,NaN,1540056,98505,18850.79,6.40,0.1914,12.24
11,Video,DV360,NaN,NaN,1297426,81190,14803.24,6.26,0.1823,11.41
12,Search,Google Ads,NaN,NaN,1444034,89361,16003.26,6.19,0.1791,11.08
13,Mobile,Facebook Ads,NaN,NaN,1451264,88427,17088.44,6.09,0.1932,11.77
14,Display,Google Ads,NaN,NaN,1156388,67804,13774.90,5.86,0.2032,11.91
15,Video,DV360,300.0,250.0,5303703,180519,40456.76,3.40,0.2241,7.63
16,Search,DV360,300.0,250.0,5014245,157618,39641.52,3.14,0.2515,7.91
17,Search,Google Ads,300.0,250.0,4865678,151816,37254.11,3.12,0.2454,7.66
18,Display,Facebook Ads,300.0,250.0,4914746,152990,38548.92,3.11,0.2520,7.84
19,Mobile,DV360,300.0,250.0,5112591,155837,40460.83,3.05,0.2596,7.91
20,Social,DV360,300.0,250.0,4827351,143680,36826.41,2.98,0.2563,7.63
21,Display,Google Ads,300.0,250.0,4884252,145596,38020.63,2.98,0.2611,7.78
22,Video,Facebook Ads,300.0,250.0,4517693,132465,34787.73,2.93,0.2626,7.70
23,Social,Facebook Ads,300.0,250.0,5126577,148294,39810.55,2.89,0.2685,7.77
24,Video,Google Ads,300.0,250.0,5073423,143029,40570.55,2.82,0.2837,8.00
25,Mobile,Facebook Ads,300.0,250.0,5217071,143333,43479.62,2.75,0.3033,8.33
26,Social,Google Ads,300.0,250.0,4532513,122247,34528.05,2.70,0.2824,7.62
27,Display,DV360,300.0,250.0,4641307,125206,35868.43,2.70,0.2865,7.73
28,Mobile,Google Ads,300.0,250.0,4720347,125159,36408.19,2.65,0.2909,7.71
29,Search,Facebook Ads,300.0,250.0,4679331,120292,36811.98,2.57,0.3060,7.87
30,Video,Facebook Ads,0.0,0.0,333935,6364,2859.78,1.91,0.4494,8.56
31,Display,DV360,0.0,0.0,331092,6304,2564.55,1.90,0.4068,7.75
32,Social,Facebook Ads,0.0,0.0,361519,6704,3005.03,1.85,0.4482,8.31
33,Mobile,Facebook Ads,0.0,0.0,358669,6378,3172.87,1.78,0.4975,8.85
34,Video,Google Ads,0.0,0.0,365164,6465,2900.73,1.77,0.4487,7.94
35,Search,Facebook Ads,0.0,0.0,358297,6263,2925.38,1.75,0.4671,8.16
36,Mobile,DV360,0.0,0.0,350628,6117,3082.00,1.74,0.5038,8.79
37,Social,DV360,0.0,0.0,333221,5688,2904.13,1.71,0.5106,8.72
38,Display,Facebook Ads,0.0,0.0,350414,5886,2749.37,1.68,0.4671,7.85
39,Search,DV360,0.0,0.0,361702,6091,3021.31,1.68,0.4960,8.35
40,Search,Google Ads,0.0,0.0,367953,6020,3293.50,1.64,0.5471,8.95
41,Video,DV360,0.0,0.0,355044,5668,3064.28,1.60,0.5406,8.63
42,Display,Google Ads,0.0,0.0,333475,5306,2602.08,1.59,0.4904,7.80
43,Social,Google Ads,0.0,0.0,352164,5372,2605.70,1.53,0.4851,7.40
44,Mobile,Google Ads,0.0,0.0,348253,5317,2935.57,1.53,0.5521,8.43